---
kind: pipeline
name: "toy-bot coding challenge pipeline"
steps:
  -
    commands:
      - "mvn clean test"
    image: "maven:3-openjdk-18"
    name: test
  -
    image: appleboy/drone-telegram
    name: "send telegram notification"
    settings:
      to:
        from_secret: telegram_to
      token:
        from_secret: telegram_token